
// export const sample_Mens: any[]=[
//    { id:'1',
//    name:'cap',
//    description:'this is cap',
//    price:2700,
//    MRP:3000,
//    off:10,
//    tag:['cotten'],
//    favorite:false,
//    stars:5,
//    imageUrl:'https://m.media-amazon.com/images/I/71NpaEOdgxL._AC_UY1100_.jpg',
//    origins:['gujarat'],
//    deliverTime:['1-2']
//   },
//   { id:'2',
//    name:'men-tshirt',
//    description:'this is LV New tshirt',
//    price:100000,
//    MRP:115000,
//    off:15000,
//    tag:['cotten','tshirt'],
//    favorite:false,
//    stars:5,
//    imageUrl:'https://assets.ajio.com/medias/sys_master/root/20231214/xIDk/657ad736afa4cf41f5cff63e/-473Wx593H-464531848-navy-MODEL.jpg',
//    origins:['gujarat'],
//    deliverTime:['1-2']
//   },
// ]


// export const sample_products: any[]=[
//    { id:'1',
//     name:'shirt',
//     description:'this is blue t-shirt',
//     price:2700,
//     MRP:3000,
//     off:10,
//     tag:['cotten',+'shirt'],
//     favorite:false,
//     stars:5,
//     imageUrl:'assets/blank-t-shirts.jpg',
//     origins:['gujarat'],
//     deliverTime:['1-2']
//    },
//    { id:'2',
//     name:'iphone',
//     description:'this is iphone mobile',
//     price:112000,
//     MRP:140000,
//     off:20,
//     tag:['Mobiles'],
//     favorite:false,
//     stars:4,
//     imageUrl:'assets/new Iphone.png',
//     origins:['gujarat'],
//     deliverTime:['1-3']
//    },
   
//    { id:'3',
//     name:'shoes',
//     description:'this is nike shoes',
//     price:2000,
//     MRP:2500,
//     off:20,
//     tag:['shoes'],
//     favorite:true,
//     stars:1,
//     imageUrl:'https://m.media-amazon.com/images/I/7102q4bLwFL._AC_UY1000_.jpg',
//     origins:['new york'],
//     deliverTime:['5-8']
//    },
//    { id:'4',
//     name:'simple Watch',
//     description:'this is simple  watch',
//     price:7999,
//     MRP:9999,
//     off:20,
//     tag:['watch'],
//     favorite:false,
//     stars:3,
//     imageUrl:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2F0Y2h8ZW58MHx8MHx8fDA%3D',
//     origins:['china'],
//     deliverTime:['10-12']
//    },
//    { id:'5',
//     name:'headphones',
//     description:'this is blue headphones',
//     price:16000,
//     MRP:20000,
//     off:20,
//     tag:['headphones'+'nokia'],
//     favorite:true,
//     stars:4,
//     imageUrl:'assets/images.jpeg',
//     origins:['kutch'],
//     deliverTime:['2-4']
//    },
//    { id:'6',
//     name:'Digital watch',
//     description:'this is digital watch',
//     price:79999,
//     MRP:99999,
//     off:20,
//     tag:['watch','Digital Watch'],
//     favorite:false,
//     stars:3,
//     imageUrl:'assets/DG1.jpg',
//     origins:['london'],
//     deliverTime:['7-9']
//    },
//    { id:'7',
//     name:'charger',
//     description:'Vivo Z1x charger',
//     price:1120,
//     MRP:1400,
//     off:280,
//     tag:['charger'],
//     favorite:false,
//     stars:5,
//     imageUrl:'https://m.media-amazon.com/images/I/51QLU+bV6vL._AC_UF1000,1000_QL80_.jpg',
//     origins:['gujarat'],
//     deliverTime:['1-9']
//    },
//    { id:'8',
//     name:'wireless headphones',
//     description:'this is wireless new headphones',
//     price:20000,
//     MRP:22000,
//     off:2000,
//     tag:['headphones'],
//     favorite:false,
//     stars:4,
//     imageUrl:'https://m.media-amazon.com/images/I/41tp0JPPlmL._AC_UF1000,1000_QL80_.jpg',
//     origins:['gujarat'],
//     deliverTime:['1-3']
//    },
//    { id:'9',
//     name:'Laptop',
//     description:'16GB RAM',
//     price:110000,
//     MRP:115000,
//     off:5000,
//     tag:['laptop'],
//     favorite:false,
//     stars:3,
//     imageUrl:'https://images.samsung.com/is/image/samsung/p6pim/in/feature/164358796/in-feature-galaxy-book3-360-15-6-inch-with-s-pen-np750-535677027?$FB_TYPE_A_MO_JPG$',
//     origins:['Ahmedabad'],
//     deliverTime:['7-8']
//    },
// ]

 

// export const sample_tags: any[]=
// [
//    {name:'All', count:6},
//    {name:'Simple watch', count:1},
//    {name:'headphones', count:1},
//    {name:'Digital watch', count:1},
//    {name:'shirt', count:1},
//    {name:'jeans', count:1},
//    {name:'iphone', count:1},
//    {name:'shoes', count:1},
//    {name:'laptop', count:1},
// ]
// export const sample_Mens: any[]=[
//    { id:'1',
//    name:'cap',
//    description:'this is cap',
//    price:2700,
//    MRP:3000,
//    off:10,
//    tag:['cotten'],
//    favorite:false,
//    stars:5,
//    imageUrl:'https://m.media-amazon.com/images/I/71NpaEOdgxL._AC_UY1100_.jpg',
//    origins:['gujarat'],
//    deliverTime:['1-2']
//   },
//   { id:'2',
//    name:'men-tshirt',
//    description:'this is LV New tshirt',
//    price:100000,
//    MRP:115000,
//    off:15000,
//    tag:['cotten','tshirt'],
//    favorite:false,
//    stars:5,
//    imageUrl:'https://assets.ajio.com/medias/sys_master/root/20231214/xIDk/657ad736afa4cf41f5cff63e/-473Wx593H-464531848-navy-MODEL.jpg',
//    origins:['gujarat'],
//    deliverTime:['1-2']
//   },
// ]


// export const sample_products: any[]=[
//    { 
//     name:'shirt',
//     description:'this is blue t-shirt',
//     price:27,
//     MRP:32,
//     off:5,
//     tag:['cotten',+'shirt'],
//     favorite:false,
//     stars:5,
//     imageUrl:'assets/blank-t-shirts.jpg',
//     origins:['gujarat'],
//     deliverTime:['1-2']
//    },
//    { 
//     name:'iphone',
//     description:'this is iphone mobile',
//     price:1120,
//     MRP:1200,
//     off:80,
//     tag:['Mobiles'],
//     favorite:false,
//     stars:4,
//     imageUrl:'assets/new Iphone.png',
//     origins:['gujarat'],
//     deliverTime:['1-3']
//    },
   
//    { 
//     name:'shoes',
//     description:'this is nike shoes',
//     price:200,
//     MRP:250,
//     off:50,
//     tag:['shoes'],
//     favorite:true,
//     stars:1,
//     imageUrl:'https://m.media-amazon.com/images/I/7102q4bLwFL._AC_UY1000_.jpg',
//     origins:['new york'],
//     deliverTime:['5-8']
//    },
//    { 
//     name:'simple Watch',
//     description:'this is simple  watch',
//     price:799,
//     MRP:899,
//     off:100,
//     tag:['watch'],
//     favorite:false,
//     stars:3,
//     imageUrl:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2F0Y2h8ZW58MHx8MHx8fDA%3D',
//     origins:['china'],
//     deliverTime:['10-12']
//    },
//    { 
//     name:'headphones',
//     description:'this is blue headphones',
//     price:1600,
//     MRP:1825,
//     off:225,
//     tag:['headphones'+'nokia'],
//     favorite:true,
//     stars:4,
//     imageUrl:'assets/images.jpeg',
//     origins:['kutch'],
//     deliverTime:['2-4']
//    },
//    { 
//     name:'Digital watch',
//     description:'this is digital watch',
//     price:1500,
//     MRP:1725,
//     off:225,
//     tag:['watch','Digital Watch'],
//     favorite:false,
//     stars:3,
//     imageUrl:'assets/DG1.jpg',
//     origins:['london'],
//     deliverTime:['7-9']
//    },
//    { 
//     name:'charger',
//     description:'Vivo Z1x charger',
//     price:112,
//     MRP:150,
//     off:38,
//     tag:['charger'],
//     favorite:false,
//     stars:5,
//     imageUrl:'https://m.media-amazon.com/images/I/51QLU+bV6vL._AC_UF1000,1000_QL80_.jpg',
//     origins:['gujarat'],
//     deliverTime:['1-9']
//    },
//    { 
//     name:'wireless headphones',
//     description:'this is wireless new headphones',
//     price:2250,
//     MRP:2500,
//     off:250,
//     tag:['headphones'],
//     favorite:false,
//     stars:4,
//     imageUrl:'https://m.media-amazon.com/images/I/41tp0JPPlmL._AC_UF1000,1000_QL80_.jpg',
//     origins:['gujarat'],
//     deliverTime:['1-3']
//    },
//    { 
//     name:'Laptop',
//     description:'16GB RAM',
//     price:1350,
//     MRP:1500,
//     off:150,
//     tag:['laptop'],
//     favorite:false,
//     stars:3,
//     imageUrl:'https://images.samsung.com/is/image/samsung/p6pim/in/feature/164358796/in-feature-galaxy-book3-360-15-6-inch-with-s-pen-np750-535677027?$FB_TYPE_A_MO_JPG$',
//     origins:['Ahmedabad'],
//     deliverTime:['7-8']
//    },
// ]

 

export const sample_tags: any[]=
[
   {name:'All', count:6},
   {name:'Simple watch', count:1},
   {name:'headphones', count:1},
   {name:'Digital watch', count:1},
   {name:'shirt', count:1},
   {name:'jeans', count:1},
   {name:'iphone', count:1},
   {name:'shoes', count:1},
   {name:'laptop', count:1},
]


export const sample_users:any[] =[
   {
      name:"shahil",
      email:"shahilpatel688@gmail.com",
      password:"12345",
      address:"sanand",
      isAdmin:true
   },{
   name:"patel",
   email:"patel688@gmail.com",
   password:"123456",
   address:"ahmedabad",
   isAdmin:false
   }
] 